application: thegrandlocus
version: dev
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.app
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: static.app
