application: thegrandlocus
version: live
runtime: python
api_version: 1

builtins:
- deferred: on

handlers:

- url: /favicon\.ico
  static_files: themes/thegrandlocus/static/images/favicon.ico
  upload: themes/thegrandlocus/static/images/favicon\.ico

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /js
  static_dir: js

- url: /.*html$
  script: hard_html.py

- url: /.*
  script: static.py
