service: default
runtime: python39

#builtins:
#- deferred: on
#- remote_api: on
app_engine_apis: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

#- url: /_ah/queue/deferred
#  script: deferred.py
#  login: admin
#
#- url: /preview/.*
#  script: admin.app
#
#- url: /admin/.*
#  script: admin.app
#  login: admin

- url: /static
  static_dir: static

- url: .*
  script: auto
