application: thegrandlocus
version: live
runtime: python
api_version: 1

builtins:
- deferred: on

handlers:

- url: /favicon\.ico
  static_files: /thegrandlocus_theme/static/images/favicon.ico
  upload: thegrandlocus_theme/static/images/favicon\.ico

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /thegrandlocus_theme/static
  static_dir: thegrandlocus_theme/static

- url: /.*html$
  script: hard_html.py

- url: /.*
  script: static.py
